# Generated by Django 5.2.8 on 2025-12-27 11:00

from django.db import migrations
from decimal import Decimal


def fill_penalty(apps, schema_editor):
    Borrowing = apps.get_model('main', 'Borrowing')
    
    for b in Borrowing.objects.all():
        if b.actual_return_date and b.actual_return_date > b.return_date:
            days_late = (b.actual_return_date - b.return_date).days
            b.penalty = Decimal(days_late * 1)  # 1 currency unit per day
        else:
            b.penalty = Decimal('0.00')
        b.save()

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_squashed_0005_alter_book_options_book_is_published'),
    ]

    operations = [
        migrations.RunPython(fill_penalty),
    ]
