# Generated by Django 5.2.8 on 2025-12-27 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20251227_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='digital_book',
            field=models.FileField(blank=True, null=True, upload_to='digital_books/'),
        ),
    ]
